'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ItemsComponents
    Public Property Id As Integer
    Public Property SkuComponent As String
    Public Property ItemDescription As String
    Public Property Quantity As Decimal
    Public Property UM As String
    Public Property ItemsId As Integer
    Public Property StndCost As Double
    Public Property CurrCost As Double
    Public Property Result As Double
    Public Property Lvl1 As Integer
    Public Property Lvl2 As Integer
    Public Property Lvl3 As Integer

End Class
