'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CoflexDBEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CoflexDBEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Items() As DbSet(Of Items)
    Public Overridable Property ItemsComponents() As DbSet(Of ItemsComponents)
    Public Overridable Property Quotations() As DbSet(Of Quotations)
    Public Overridable Property QuotationVersions() As DbSet(Of QuotationVersions)
    Public Overridable Property AspNetUsersView() As DbSet(Of AspNetUsersView)
    Public Overridable Property NewComponents() As DbSet(Of NewComponents)
    Public Overridable Property NewComponentsView() As DbSet(Of NewComponentsView)
    Public Overridable Property CatUOFMView() As DbSet(Of CatUOFMView)
    Public Overridable Property QuotationSummaryView() As DbSet(Of QuotationSummaryView)

End Class
