'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class CoflexDBEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CoflexDBEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Items() As DbSet(Of Items)
    Public Overridable Property ItemsComponents() As DbSet(Of ItemsComponents)
    Public Overridable Property Quotations() As DbSet(Of Quotations)
    Public Overridable Property QuotationVersions() As DbSet(Of QuotationVersions)
    Public Overridable Property AspNetUsersView() As DbSet(Of AspNetUsersView)
    Public Overridable Property NewComponents() As DbSet(Of NewComponents)
    Public Overridable Property NewComponentsView() As DbSet(Of NewComponentsView)
    Public Overridable Property CatUOFMView() As DbSet(Of CatUOFMView)
    Public Overridable Property QuotationSummaryView() As DbSet(Of QuotationSummaryView)
    Public Overridable Property Prospect() As DbSet(Of Prospect)
    Public Overridable Property QuoteComments() As DbSet(Of QuoteComments)

    Public Overridable Function Indicator(mindate As Nullable(Of Date), maxdate As Nullable(Of Date), estatus As String, estatusV As String, vendedor As String, cliente As String) As ObjectResult(Of Indicator_Result)
        Dim mindateParameter As ObjectParameter = If(mindate.HasValue, New ObjectParameter("mindate", mindate), New ObjectParameter("mindate", GetType(Date)))

        Dim maxdateParameter As ObjectParameter = If(maxdate.HasValue, New ObjectParameter("maxdate", maxdate), New ObjectParameter("maxdate", GetType(Date)))

        Dim estatusParameter As ObjectParameter = If(estatus IsNot Nothing, New ObjectParameter("estatus", estatus), New ObjectParameter("estatus", GetType(String)))

        Dim estatusVParameter As ObjectParameter = If(estatusV IsNot Nothing, New ObjectParameter("estatusV", estatusV), New ObjectParameter("estatusV", GetType(String)))

        Dim vendedorParameter As ObjectParameter = If(vendedor IsNot Nothing, New ObjectParameter("vendedor", vendedor), New ObjectParameter("vendedor", GetType(String)))

        Dim clienteParameter As ObjectParameter = If(cliente IsNot Nothing, New ObjectParameter("cliente", cliente), New ObjectParameter("cliente", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Indicator_Result)("Indicator", mindateParameter, maxdateParameter, estatusParameter, estatusVParameter, vendedorParameter, clienteParameter)
    End Function

End Class
