'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NewComponents
    Public Property Id As Integer
    Public Property SkuComponente As String
    Public Property IdQuotation As Integer
    Public Property Uofm As String
    Public Property StndCost As Decimal
    Public Property CurrntCost As Decimal
    Public Property Result As Decimal

End Class
