'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class QuotationSummaryView
    Public Property Id As Integer
    Public Property CoflexId As String
    Public Property ClientId As String
    Public Property ClientName As String
    Public Property Status As Integer
    Public Property Vendor As String
    Public Property IdVersion As Integer
    Public Property VersionNumber As Integer
    Public Property ExchangeRate As Double
    Public Property [Date] As Date
    Public Property LastModificationDate As Date
    Public Property VStatus As Integer
    Public Property Margin As Nullable(Of Double)
    Public Property QuotationStatusName As String
    Public Property QuotationVersionStatusName As String

End Class
