'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class QuoteComments
    Public Property Id As Integer
    Public Property QuotationsVersionsId As Integer
    Public Property Atention As String
    Public Property Configuration As String
    Public Property OrderDeliery As String
    Public Property DeliveryTerms As String
    Public Property ValidOffer As String

End Class
