'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Quotation
    Public Property Id As Integer
    Public Property AspNetUsersId As String
    Public Property ClientId As String
    Public Property [Date] As Date
    Public Property Status As Integer = 0

    Public Overridable Property QuotationVersion As ICollection(Of QuotationVersion) = New HashSet(Of QuotationVersion)

End Class
