'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VistaItemComponents
    Public Property SkuArticulo As String
    Public Property SkuComponente As String
    Public Property ITEMDESC As String
    Public Property QUANTITY_I As Nullable(Of Decimal)
    Public Property UOFM As String
    Public Property STNDCOST As Decimal
    Public Property CURRCOST As Decimal
    Public Property RESULT As Nullable(Of Decimal)
    Public Property Nivel1 As Nullable(Of Short)
    Public Property Nivel2 As Nullable(Of Integer)
    Public Property Nivel3 As Nullable(Of Integer)

End Class
